// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// CRFamily
arma::vec CRFamily(arma::vec x, double theta);
RcppExport SEXP _ATE_CRFamily(SEXP xSEXP, SEXP thetaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type x(xSEXP);
    Rcpp::traits::input_parameter< double >::type theta(thetaSEXP);
    rcpp_result_gen = Rcpp::wrap(CRFamily(x, theta));
    return rcpp_result_gen;
END_RCPP
}
// CRFamilyDerivative
arma::vec CRFamilyDerivative(arma::vec x, double theta);
RcppExport SEXP _ATE_CRFamilyDerivative(SEXP xSEXP, SEXP thetaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type x(xSEXP);
    Rcpp::traits::input_parameter< double >::type theta(thetaSEXP);
    rcpp_result_gen = Rcpp::wrap(CRFamilyDerivative(x, theta));
    return rcpp_result_gen;
END_RCPP
}
// CRFamilySecondDerivative
arma::vec CRFamilySecondDerivative(arma::vec x, double theta);
RcppExport SEXP _ATE_CRFamilySecondDerivative(SEXP xSEXP, SEXP thetaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type x(xSEXP);
    Rcpp::traits::input_parameter< double >::type theta(thetaSEXP);
    rcpp_result_gen = Rcpp::wrap(CRFamilySecondDerivative(x, theta));
    return rcpp_result_gen;
END_RCPP
}
// ObjectiveFunction
double ObjectiveFunction(NumericVector lam, NumericMatrix u, NumericVector ubar, arma::vec treat, double theta);
RcppExport SEXP _ATE_ObjectiveFunction(SEXP lamSEXP, SEXP uSEXP, SEXP ubarSEXP, SEXP treatSEXP, SEXP thetaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type lam(lamSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type u(uSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type ubar(ubarSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type treat(treatSEXP);
    Rcpp::traits::input_parameter< double >::type theta(thetaSEXP);
    rcpp_result_gen = Rcpp::wrap(ObjectiveFunction(lam, u, ubar, treat, theta));
    return rcpp_result_gen;
END_RCPP
}
// ObjectiveFirstDerivative
arma::rowvec ObjectiveFirstDerivative(NumericVector lam, NumericMatrix u, NumericVector ubar, arma::vec treat, double theta);
RcppExport SEXP _ATE_ObjectiveFirstDerivative(SEXP lamSEXP, SEXP uSEXP, SEXP ubarSEXP, SEXP treatSEXP, SEXP thetaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type lam(lamSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type u(uSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type ubar(ubarSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type treat(treatSEXP);
    Rcpp::traits::input_parameter< double >::type theta(thetaSEXP);
    rcpp_result_gen = Rcpp::wrap(ObjectiveFirstDerivative(lam, u, ubar, treat, theta));
    return rcpp_result_gen;
END_RCPP
}
// UpdateInverseHessian
arma::mat UpdateInverseHessian(arma::mat old_inv_hessian, arma::vec diff_in_est, arma::vec diff_in_derv);
RcppExport SEXP _ATE_UpdateInverseHessian(SEXP old_inv_hessianSEXP, SEXP diff_in_estSEXP, SEXP diff_in_dervSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type old_inv_hessian(old_inv_hessianSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type diff_in_est(diff_in_estSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type diff_in_derv(diff_in_dervSEXP);
    rcpp_result_gen = Rcpp::wrap(UpdateInverseHessian(old_inv_hessian, diff_in_est, diff_in_derv));
    return rcpp_result_gen;
END_RCPP
}
// BacktrackLineSearch
double BacktrackLineSearch(double kAlpha, double kBeta, NumericVector current_est, NumericVector current_direction, NumericVector current_derv, NumericMatrix u, NumericVector ubar, arma::vec treat, double theta);
RcppExport SEXP _ATE_BacktrackLineSearch(SEXP kAlphaSEXP, SEXP kBetaSEXP, SEXP current_estSEXP, SEXP current_directionSEXP, SEXP current_dervSEXP, SEXP uSEXP, SEXP ubarSEXP, SEXP treatSEXP, SEXP thetaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type kAlpha(kAlphaSEXP);
    Rcpp::traits::input_parameter< double >::type kBeta(kBetaSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type current_est(current_estSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type current_direction(current_directionSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type current_derv(current_dervSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type u(uSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type ubar(ubarSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type treat(treatSEXP);
    Rcpp::traits::input_parameter< double >::type theta(thetaSEXP);
    rcpp_result_gen = Rcpp::wrap(BacktrackLineSearch(kAlpha, kBeta, current_est, current_direction, current_derv, u, ubar, treat, theta));
    return rcpp_result_gen;
END_RCPP
}
// BFGSAlgorithm
List BFGSAlgorithm(NumericVector initial, NumericMatrix u, NumericVector ubar, arma::vec treat, double theta, double kAlpha, double kBeta, int max_iter, double tol);
RcppExport SEXP _ATE_BFGSAlgorithm(SEXP initialSEXP, SEXP uSEXP, SEXP ubarSEXP, SEXP treatSEXP, SEXP thetaSEXP, SEXP kAlphaSEXP, SEXP kBetaSEXP, SEXP max_iterSEXP, SEXP tolSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type initial(initialSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type u(uSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type ubar(ubarSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type treat(treatSEXP);
    Rcpp::traits::input_parameter< double >::type theta(thetaSEXP);
    Rcpp::traits::input_parameter< double >::type kAlpha(kAlphaSEXP);
    Rcpp::traits::input_parameter< double >::type kBeta(kBetaSEXP);
    Rcpp::traits::input_parameter< int >::type max_iter(max_iterSEXP);
    Rcpp::traits::input_parameter< double >::type tol(tolSEXP);
    rcpp_result_gen = Rcpp::wrap(BFGSAlgorithm(initial, u, ubar, treat, theta, kAlpha, kBeta, max_iter, tol));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_ATE_CRFamily", (DL_FUNC) &_ATE_CRFamily, 2},
    {"_ATE_CRFamilyDerivative", (DL_FUNC) &_ATE_CRFamilyDerivative, 2},
    {"_ATE_CRFamilySecondDerivative", (DL_FUNC) &_ATE_CRFamilySecondDerivative, 2},
    {"_ATE_ObjectiveFunction", (DL_FUNC) &_ATE_ObjectiveFunction, 5},
    {"_ATE_ObjectiveFirstDerivative", (DL_FUNC) &_ATE_ObjectiveFirstDerivative, 5},
    {"_ATE_UpdateInverseHessian", (DL_FUNC) &_ATE_UpdateInverseHessian, 3},
    {"_ATE_BacktrackLineSearch", (DL_FUNC) &_ATE_BacktrackLineSearch, 9},
    {"_ATE_BFGSAlgorithm", (DL_FUNC) &_ATE_BFGSAlgorithm, 9},
    {NULL, NULL, 0}
};

RcppExport void R_init_ATE(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
