# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

CRFamily <- function(x, theta) {
    .Call('ATE_CRFamily', PACKAGE = 'ATE', x, theta)
}

CRFamilyDerivative <- function(x, theta) {
    .Call('ATE_CRFamilyDerivative', PACKAGE = 'ATE', x, theta)
}

CRFamilySecondDerivative <- function(x, theta) {
    .Call('ATE_CRFamilySecondDerivative', PACKAGE = 'ATE', x, theta)
}

ObjectiveFunction <- function(lam, u, ubar, treat, theta) {
    .Call('ATE_ObjectiveFunction', PACKAGE = 'ATE', lam, u, ubar, treat, theta)
}

ObjectiveFirstDerivative <- function(lam, u, ubar, treat, theta) {
    .Call('ATE_ObjectiveFirstDerivative', PACKAGE = 'ATE', lam, u, ubar, treat, theta)
}

UpdateInverseHessian <- function(old_inv_hessian, diff_in_est, diff_in_derv) {
    .Call('ATE_UpdateInverseHessian', PACKAGE = 'ATE', old_inv_hessian, diff_in_est, diff_in_derv)
}

BacktrackLineSearch <- function(kAlpha, kBeta, current_est, current_direction, current_derv, u, ubar, treat, theta) {
    .Call('ATE_BacktrackLineSearch', PACKAGE = 'ATE', kAlpha, kBeta, current_est, current_direction, current_derv, u, ubar, treat, theta)
}

BFGSAlgorithm <- function(initial, u, ubar, treat, theta, kAlpha, kBeta, max_iter, tol) {
    .Call('ATE_BFGSAlgorithm', PACKAGE = 'ATE', initial, u, ubar, treat, theta, kAlpha, kBeta, max_iter, tol)
}

