# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cpp_cr_rho <- function(x, theta) {
    .Call('ATE_cpp_cr_rho', PACKAGE = 'ATE', x, theta)
}

cpp_dcr_rho <- function(x, theta) {
    .Call('ATE_cpp_dcr_rho', PACKAGE = 'ATE', x, theta)
}

cpp_ddcr_rho <- function(x, theta) {
    .Call('ATE_cpp_ddcr_rho', PACKAGE = 'ATE', x, theta)
}

cpp_obj <- function(lam, u, ubar, Ti, theta) {
    .Call('ATE_cpp_obj', PACKAGE = 'ATE', lam, u, ubar, Ti, theta)
}

cpp_derv_obj <- function(lam, u, ubar, Ti, theta) {
    .Call('ATE_cpp_derv_obj', PACKAGE = 'ATE', lam, u, ubar, Ti, theta)
}

cpp_update_hessianInv <- function(oldInv, sk, yk) {
    .Call('ATE_cpp_update_hessianInv', PACKAGE = 'ATE', oldInv, sk, yk)
}

cpp_backtrack <- function(alpha, beta, x_val, del_x, nabla_f, u, ubar, Ti, theta) {
    .Call('ATE_cpp_backtrack', PACKAGE = 'ATE', alpha, beta, x_val, del_x, nabla_f, u, ubar, Ti, theta)
}

cpp_quasi_newt <- function(ini, u, ubar, Ti, theta, alpha, beta, max_iter, tol) {
    .Call('ATE_cpp_quasi_newt', PACKAGE = 'ATE', ini, u, ubar, Ti, theta, alpha, beta, max_iter, tol)
}

